### PR TITLE
Migrate to SPA architecture using Svelte

### PR DESCRIPTION
**Pull request by toboshii**

### CODE REVIEW

**Comment by fastlorenzo** [comment]
@toboshii thanks for the awesome app! I've been trying to build it from this branch in a fork, but it looks like the only thing that is currently working with the Dockerfile (I've had to slightly modify it to make it compile) is the backend.
With this rework, do you plan to have 2 containers (1 to serve the frontend and the other for the backend)?

**Comment by fastlorenzo** [comment]
> > @toboshii thanks for the awesome app! I've been trying to build it from this branch in a fork, but it looks like the only thing that is currently working with the Dockerfile (I've had to slightly modify it to make it compile) is the backend. With this rework, do you plan to have 2 containers (1 to serve the frontend and the other for the backend)?
> 
> Thanks for the kind words, and trying Hajimari out! Yes I haven't quite updated the build process yet as I just run the frontend and backend separately for dev. The plan is to continue embedding the frontend as was done previously. In the latest code I've pushed this is completed.
> 
> I'm hoping to have the time this weekend to wrap most of this up and get a beta build out this week.

Awesome work, thanks! I finally managed to build and test the latest changes, looks promising! I'll make sure to provide any relevant feedback as I'm using it ;)

**Comment by fastlorenzo** [comment]
FYI - some permissions need to be added to the service account:

```
hajimari-5c4bf99964-qr5z8 hajimari time="2022-10-02T00:51:09Z" level=error msg="Error Getting EndpointSlices: endpointslices.discovery.k8s.io is forbidden: User \"system:serviceaccount:default:hajimari\" cannot list resource \"endpointslices\" in API group \"discovery.k8s.io\" in the namespace \"rook-ceph\"" _source="util/replicastatusgetter.go:55"
```

**Comment by toboshii** [comment]
> FYI - some permissions need to be added to the service account:

Thanks for pointing that out, I'll make sure that gets in the next chart release :+1:

**Pull request merged**
