### PR TITLE
Add status indicators to hajimari apps

### LINKED ISSUE #20: Add status/health of services
While showing Kubernetes services is fine, it would be great if you also got some sort of health indicator for them.

So you can see a green checkmark or green icon next to each service.

There are many ways to check health in Kubernetes (count number of active pods, curl the service, define healthcheck etc)

### PR DESCRIPTION
**Pull request by h3mmy**
# Description

This PR adds status indicators to the dashboard. There is a passive feature toggle-ish setting currently defaulting to true that can be flipped if desired.

## Type of Change

Feature: ~~Non-Breaking~~ Change that adds functionality. While the annotation parser defaults to true, this could be considered slightly breaking as it could cause things to not work as expected.
It will require some documentation update(s)

## Issues pertaining to this PR

technically resolves #20 

## Other Notes

- Tested against k3s v1.23.3. Used Vivaldi and Chrome.
- There may be a method or two that are extraneous as it was for a templating thing I was trying to do that hasn't worked yet.
- I'm hoping to eventually build on this to segment the indicator based on # of replicas and have the indicators work for each. 
- Indicators do not refresh live. It uses the state it gets when the page loads.

I'm happy to add more unit tests or make tweaks if you want me to before this is merged. I'm also happy to make tweaks and improvements after provided an issue is defined for it. 

sample_indicators_draft_1

### CODE REVIEW

**Comment by khuedoan** [comment]
Thank you so much for your efforts, this is a fantastic feature!

Do you think it will look cleaner if we use simple dots like the mock up below? (just my personal opinion, please ignore if you don't)

mockup_hajimari

**Comment by khuedoan** [comment]
I think we can use multiple dots or multiple colors:

- green: all replicas are available
- orange: at least 1 replica is available
- red: none available

**Comment by h3mmy** [comment]
@toboshii Is that something you want me to add in this PR or keep it for the next PR as the replica detection is new functionality?

**Comment by h3mmy** [comment]
Closing in favor of #45

**Pull request closed without merging**
